config/routes.rb
Rails.application.routes.draw do
  get "about-us", to: "about#index", as: :about

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "auth/twitter/callback", to: "omniauth_callbacks#twitter"
  
  resources :twitter_accounts
  #get "twitter_accounts/:id"
  #delete "twitter_accounts/:id"

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    # this class you use in your requests to assign things: user, timezone, what account 
    # they are on and other details that pertain to the current request
    # if logged in, current.user != nil
    attribute :user
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  validates :username, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    # virtual atributes: password and password_confirmation - we only 
    # iteract with them when creating a user
    has_many :twitter_accounts
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    # before is a method that makes sure set_current_user is done before any action 
    
    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
            # changed this line: @user = User.find_by(id: session[:user_id])
            # create current model
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in to do that" if Current.user.nil?
        # redirect user to login if they are not there
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        # verify if there is already an account for that twitter account
        twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
        twitter_account.update(
            name: auth.info.name,
            username: auth.info.nickname,
            image: auth.info.image,
            token: auth.credentials.token,
            secret: auth.credentials.secret,
        )

        redirect_to twitter_accounts_path, notice: "Successfully connected to your account"
    end

    def auth
        request.env['omniauth.auth'] # setted by omniauth gem
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end
    
    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_later # or deliver_now
            # PasswordMailer - class
            # with - include parameters - who to send to
            # reset - reset mail with user
            # deliver_later - send this in background job, so our request can happen imediately
            # email takes some seconds to be sent
        end
        redirect_to root_path, notice: "If an account is found, we have sent a link to reset your password"
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id  # encript session
            redirect_to root_path, notice: "Welcome, you signed up!"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
 class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in successfully"
        else
            redirect_to sign_in_path, notice: "Invalid email or password"
        end

    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You logged out"
    end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_twitter_account, only: [:destroy]
    
    def index
        @twitter_accounts = Current.user.twitter_accounts
    end

    def destroy
        @twitter_account.destroy
        redirect_to twitter_accounts_path, notice: "Successfully disconnected @#{@twitter_account.username}"
    end

    private

    def set_twitter_account
        @twitter_account = Current.user.twitter_accounts.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center pt-4">
    <h1>Welcome to tweet this later!</h1>

</div>
<div class="d-flex align-items-center justify-content-center pt-4">
    <%= button_to "Connect Twitter", "/auth/twitter", method: :post, class:"btn btn-primary" %>

</div>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control", placeholder: "password" %>
  </div>

  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div
<% end %>

app/views/password_resets/new.html.erb
<div class="pt-3"><h1>Forgot your password?</h1></div>

<%= form_with url: password_reset_path do |form| %>
    <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class:"form-control", placeholder: "louise@mail.com" %>
    </div>
    <div class="mb-3">
        <%= form.submit "Reset password", class:"btn btn-outline-info" %>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Tweet this later</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Twitter Accounts", twitter_accounts_path, class:"nav-link active" %>
      </div>
      <div class="navbar-nav">
        <%= link_to "About us", about_path, class:"nav-link active" %>
      </div>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user%>
          <li class="nav-item">
          <%= link_to Current.user.email, edit_password_path %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class:"btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", sign_in_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
          </li>
        <% end %>
    </div>
  </div>
</nav>

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
<h1> Twitter Accounts </h1>
<%= link_to "Connect a twitter account", "/auth/twitter", method: :post, class:"btn btn-primary" %>
<% @twitter_accounts.each do |twitter_account| %>
    <div class="d-flex align-items-center mb-4">
        <div class="me-4">
            <%= image_tag twitter_account.image, class:"rounded-circle" %>
            <%= link_to "@#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
        </div>
        <%= button_to "Disconnect", twitter_account, method: :delete %>
    </div>
<% end %>